### ISSUE TITLE
Configure Dependabot

### ISSUE THREAD

**Issue by vil02** [OpenElements/hedera-enterprise#42]
The [`actions/setup-java`](https://github.com/actions/setup-java) is out of date in:
https://github.com/OpenElements/hedera-enterprise/blob/aeefb188744e2e132d6b4820bf186ae6bae972ea/.github/workflows/maven.yml#L27

This is a good opportunity to configure dependabot for this repository to keep github actions up to date because we would be able to verify immediately the setup. The basic config could look like this:
```yml
---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
...
```
